name: Fairseq Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release Type'
        default: 'patch'
        required: true

  push:
    branches:
      - v[0-9]+.[0-9]+.[x0-9]+
    tags:
      - v*
